name: Slack_New_try_with_reporting-2

on: 
  workflow_dispatch:
    inputs:
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg 
 
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       PROVAR_HOME: ${{ github.workspace }}/ProvarHome
       
    strategy:
      fail-fast: false
      matrix:
        Plan: ["Shop Floor"]  	
    
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H_%M_%S')"

    - name: Set Plan Name
      id: PlanName
      run: |
        temp="${{matrix.Plan}}"	
        echo "::set-output name=PlanName::$(echo ${temp// /_})"    

    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8

    
    - name: Send Slack Message
      uses: archive/github-actions-slack@master
      id: send-message

      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
        slack-channel: C03KF4U7TSP
        slack-text: Execution Started for Test Plan ${{ steps.PlanName.outputs.PlanName}} at ${{ steps.date.outputs.date }}

    - name: Send "Slack Message" Result
      run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"

    - name: Execute Test Plan-${{matrix.Plan}}
      run: |
        echo "Test Plan Name Env Var--:"${{ steps.PlanName.outputs.PlanName}}
        mkdir $GITHUB_WORKSPACE/ProvarHome
        curl -O https://download.provartesting.com/2.6.2/Provar_ANT_2.6.2.02.zip
        unzip -o Provar_ANT* -d ProvarHome
        rm Provar_ANT_*
        sudo apt-get update && sudo apt-get upgrade       
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -        
        sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >>sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get -y install google-chrome-stable
        echo $PROVAR_HOME
        cd $GITHUB_WORKSPACE/ANT
        echo "Selected Plan Name="${{matrix.Plan}}
        echo "Selected Environment is="${{ github.event.inputs.TestEnv }}
        xvfb-run ant -file build.xml "-DTestEnv=${{ github.event.inputs.TestEnv }}" "-DTestPlan=${{matrix.Plan}}" runtests
   

    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      id: test-report               # Set ID reference for step
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: ${{ github.workspace }}/ANT/Results/JUnit html/TESTS-TestSuites.xml    # Path to test results
        reporter: jest-junit        # Format of test results

    - name: Send Thread Message
      uses: archive/github-actions-slack@master
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
        slack-channel: ${{ fromJson(steps.send-message.outputs.slack-result).response.channel }}
        slack-text: ${{github.run_attempt}}-${{job.status}}
        slack-optional-thread_ts: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}
        #slack-optional-reply_broadcast: true # To broadcast thread reply in channel

    - name: Send "Send Thread Message" Result
      run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"

    - name: Rename PDF File
      if: ${{ always() }}
      run: |
        cd $GITHUB_WORKSPACE/ANT/Results/Artifacts/
        mv *.pdf ${{ steps.PlanName.outputs.PlanName}}-${{ steps.date.outputs.date }}.pdf
        echo "-----List of file After Rename-----"
        ls -a
        
    - name: Upload PDF Report To Slack
      uses: adrey/slack-file-upload-action@master
      if: ${{ always() }}
      with:
       token: ${{ secrets.SLACK_TOKEN }}
       path: ${{ github.workspace }}/ANT/Results/Artifacts/${{ steps.PlanName.outputs.PlanName}}-${{ steps.date.outputs.date }}.pdf
       channel: provar-gitaction
       title: PDF Report-${{matrix.Plan}}-${{ steps.date.outputs.date }}

    - name: Compressing Results folder(Create Zip File)
      if: ${{ always() }}
      run: |
        cd $GITHUB_WORKSPACE/ANT
        echo "compressing Results folder"
        zip -v -r Execution_Report_for_${{github.workflow}}_${{ steps.PlanName.outputs.PlanName}}-${{ steps.date.outputs.date }}_${{github.run_attempt}}-${{job.status}}.zip Results/*
        echo "-----List of file-----"
        ls -a
       
    - name: Upload Report Zip file To Slack
      uses: adrey/slack-file-upload-action@master
      if: ${{ always() }}
      with:
       token: ${{ secrets.SLACK_TOKEN }}
       path: ${{ github.workspace }}/ANT/Execution_Report_for_${{github.workflow}}_${{ steps.PlanName.outputs.PlanName}}-${{ steps.date.outputs.date }}_${{github.run_attempt}}-${{job.status}}.zip
       channel: provar-gitaction   
       
    - name: Attached Report Zip file to WorkFlow
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Execution_Report_for_${{github.workflow}}_${{matrix.Plan}}-${{ steps.date.outputs.date }}_${{github.run_attempt}}-${{job.status}}
        path: ${{ github.workspace }}/ANT/Results/*
